### ISSUE TITLE
complex key high sentinel value

### ISSUE THREAD

**Issue by rabbah** [cloudant/java-cloudant#147]
In the couchdb documentation (http://wiki.apache.org/couchdb/View_collation) a high value sentinel for complex keys is {} (as in end key = ["foo", {}]) but there appears no way to set this on a Key.ComplexKey in the cloudant API v 2.0. Am I missing something?

The Cloudant REST API supports {}.

**Comment by ricellis** [comment]
Thanks for pointing this out you are correct there is no way to set this. We'll look at getting something added to `ComplexKey` to support this.

**Comment by eli-jordan** [comment]
This is something I just hit too. I just invoked the addObjects method on ComplexKey using reflection (for not). SO maybe just exposing that method as public is good enough.

**Comment by ricellis** [comment]
It is also possible to use the String `"\ufff0"` as a high value sentinel.
For example `Key.complex("foo", "\ufff0")` should work.

**Comment by eli-jordan** [comment]
Cool I didn't know about that Unicode trick. I can remove my hacks. 

Since keys can be arbitrary json, I still think it would be useful to be able to express that with the client api

**Comment by HarikaSSS** [comment]
Hi, 
with complex key using startkey and endkey, can i extract a single record of any field?
For Instance,
startKey(Key.complex(null, "Title1", null)).endKey(Key.complex("\ufff0", "Title1", "\ufff0"))
as i have mentioned startkey and endkey both with the same value, it should return only one row with Title1. But it is returning all fields having value greater than Title1.
Is this functionality implemented wrong? or is my understanding wrong? how does it work?
how can i match a single field value when there is a complex key defined in my view?

**Comment by ricellis** [comment]
@HarikaSSS 
> with complex key using startkey and endkey, can i extract a single record of any field?

No, you cannot.

There is a [specific collation order for results in a view](http://docs.couchdb.org/en/latest/ddocs/views/collation.html). As per that collation order arrays are sorted element by element starting with the first element.

The `startkey` and `endkey` identify the bounds of a slice of the ordered results. So this means you can only filter by in-order combinations of elements. For example if your first element was identical (e.g. `"a"`) you could then filter to all the keys `["a","title1"...]`

An example ordering is:
```
"key":["a","title1","a"]
"key":["a","title1","b"]
"key":["a","title1","c"]
"key":["a","title2","a"]
"key":["a","title2","b"]
"key":["a","title2","c"]
"key":["b","title1","a"]
"key":["b","title1","b"]
"key":["b","title1","c"]
"key":["b","title2","a"]
"key":["b","title2","b"]
"key":["b","title2","c"]
```

Using the `startkey=[null, "title1"]`
Filtering of the second element only applies if the first element is the same, so in this case
a >= null so all the keys `["a", ...]` are included
b >= null so all the keys `["b", ...]` are included
regardless of the value of the second element.

If you use `startkey=["a", "title1"]` and `endkey=["a", "title2"]` you will get the results:
```
"key":["a","title1","a"]
"key":["a","title1","b"]
"key":["a","title1","c"]
```
because the title2 > title1, but note that the `["b", "title1"]` elements are not included.

So if you only need to extract based on the second element re-ordering your emit so that the title is the first element could potentially meet your needs, but you won't be able to extract an arbitrary field from a key.

The [Cloudant Query (`_find`)](https://console.bluemix.net/docs/services/Cloudant/api/cloudant_query.html#query) and [Search (`_search`)](https://console.bluemix.net/docs/services/Cloudant/api/search.html#search) endpoints may be better suited to your needs. If you need further help with understanding the principles of those types of queries and indexing or need to know more about view collation and slices I suggest you contact Cloudant support as it isn't really specific to java-cloudant.

**Comment by tomblench** [comment]
Merged to master; closing
