### ISSUE TITLE
Support text index with Query

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#166]
Support the use of text indexes with the `_find` and `_index` endpoints. 

See [Cloudant Docs](https://docs.cloudant.com/cloudant_query.html)

**Comment by ricellis** [comment]
`Database#createIndex(String indexDefinition)` does a `POST` of the `indexDefinition` string to `_index` so it should be possible to create a text index already by that means.

`Database#createIndex(String indexName, String designDocName, String indexType, IndexField[] fields)` would need some modifications to support the different `field` syntax of a text index, but there is an additional option `default_field` for  text indexes that still would not be supported by this signature. At that point we end up with a different method for text indexes, which makes the `indexType` parameter pretty pointless.

The big limitation is not being able to specify and index name or design doc for creating a text index so that could be improved. We could also possibly make improvements for constructing the index JSON string for a text index or have a function for creating the recommended (all fields) text index. However, to do that currently is not too challenging
```java
db.createIndex("{\"type\":\"text\",\"index\": {}}");
```

I can't see anything about either of the `Database#findByIndex(...)` methods that would not work with a text index.

@rhyshort was there something in particular that you thought was not supported or was it mainly the doc that said "only json as of now" that made you raise this issue?

**Comment by rhyshort** [comment]
I can't really remember, (this was a while ago) probably the only json for now, plus you need to be able to get bookmarks back from text index queries, which I don't think is support when using findByIndex iirc

**Comment by ricellis** [comment]
I've moved this to the later milestone, because I think there is a lot more API consideration that needs to happen here. As it currently stands it feels like we would have two awkward APIs and I'd rather consider a unified approach that works for either index type.

**Comment by ricellis** [comment]
A workaround for creating text indexes is documented in a duplicate issue https://github.com/cloudant/java-cloudant/issues/375#issuecomment-333768204
