### ISSUE TITLE
DesignDocumentManager is missing list functionality

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#193]
When working with design documents, we are able to get(id), put(id) and remove(id).
However there is no way to list the design documents without iterating through all the documents
in the database and checking the id (even then, nit sure the _design prefix is returned).

Would it be possible to add to DesignDocumentManager a list function : 

public List<DesignDocument> list();

The use case here is in my code base, I am building up lots of old views in my db, because I cannot easily list and remove old DD's when I apply the new views and retiring old ones, as the code evolves.

**Comment by ricellis** [comment]
I think we can consider this enhancement for a future release, but based on [this query](http://stackoverflow.com/questions/2814352/get-all-design-documents-in-couchdb) you could use this workaround in the meantime:
```java
List<String> designDocIds = database.getAllDocsRequestBuilder()
                                    .startKey("_design/")
                                    .endKey("_design0")
                                    .build()
                                    .getResponse()
                                    .getDocIds();
```
You could add `includeDocs(true)` and then use `getDocsAs(DesignDocument.class)` if you wanted a `List<DesignDocument>` instead of just the IDs.
