### ISSUE TITLE
How to configure SSL for client connection?

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#197]
When running in Websphere Liberty, with keystore enabled, the cloudant code throws an exception : 

[ERROR   ] CWPKI0022E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN CN=*.cloudant.com, OU=Engineering, O="Cloudant, Inc.", L=Boston, ST=Massachusetts, C=US was sent from the target host.  The signer might need to be added to local trust store C:/Tools/wlp-webProfile7-java8-win-x86_64-8.5.5.8/usr/servers/defaultServer/resources/security/key.jks, located in SSL configuration alias defaultSSLConfig.  The extended error message from the SSL handshake exception is: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
[ERROR   ] Failed to read cookie response header
java.security.cert.CertificateException: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
[ERROR   ] CWPKI0022E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN CN=*.cloudant.com, OU=Engineering, O="Cloudant, Inc.", L=Boston, ST=Massachusetts, C=US was sent from the target host.  The signer might need to be added to local trust store C:/Tools/wlp-webProfile7-java8-win-x86_64-8.5.5.8/usr/servers/defaultServer/resources/security/key.jks, located in SSL configuration alias defaultSSLConfig.  The extended error message from the SSL handshake exception is: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
[ERROR   ] Failed to get response code from request
java.security.cert.CertificateException: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error

This does not happen when launching the server is plain http mode with no keystore enabled.
Is there any way to configure the key to autoaccept?

The Liberty docs indicate it needs to be done on [client ](https://www-01.ibm.com/support/knowledgecenter/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_enable_ssl_liberty_client_container.html)

**Comment by ricellis** [comment]
The autoaccept option you are referring to in the Liberty docs is I believe part of running a J2EE application client container to communicate with a Liberty server. Whilst we don't have anything specific [built-in for J2EE](http://static.javadoc.io/com.cloudant/cloudant-client/2.2.0/overview-summary.html#J2EE) I would anticipate java-cloudant working as a library in a J2EE app. So just to be clear about the scenario here:

Have you included this library in a J2EE application that runs in the application client container and are having issues with the communication from that container to the Liberty server?

or

Are you having issues communicating from code running in the Liberty server to cloudant.com (which is what it looks like from the stack trace)?

In the second case my guess is that the https configuration for your Liberty server has changed the default trust store being used by the JVM and it no longer includes the root certificate you need to connect to securely to cloudant.com. If that is the case then I think there are two options:

1. Ensure that the appropriate root certificate is included in the trust store that the JVM has been configured to use (note that the default JVM trust store includes the appropriate root certificate which is why it normally works).
2. Configure java-cloudant to use a different trust store for its SSL connections instead of the modified one. You can set a custom `SSLSocketFactory` for the client to use, via the method: `ClientBuilder.customSSLSocketFactory()` before building the `CloudantClient`.

You may find the [JSSE reference guide](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html) useful if you go with option 2.

**Comment by ricellis** [comment]
I'm closing this as I don't think there is java-cloudant problem here.
