### ISSUE TITLE
Suggest updating landing page example

### ISSUE THREAD

**Issue by codyburleson** [cloudant/java-cloudant#230]
It would be helpful to add documentation on the main page (README.MD) that covers more than just saving a new document and reading a document by id. Thinking through all the most common use cases for a data driven web app, for example (Create, Read, Update, Delete, List), we probably need to use Views. Also, Is the Query API supported through this library? More examples like the following could be helpful for example (I had to dig and dig to come up with this):

```
try {
	
	ViewResponse<String, String> response = db.getViewRequestBuilder("projects","active-projects")
		.newRequest(Key.Type.STRING, String.class)
		.includeDocs(true)
		.build()
		.getResponse();
	
	List<Project> projects = response.getDocsAs(Project.class);
	for(Project project: projects) {
		System.out.println("--->" + project);
	}
	
} catch (IOException e) {
	e.printStackTrace();
}
```

For someone new to Cloudant and use of this library, more generosity with the examples would really help accelerate our learning. Please consider it because I can't even find anything anybody's built with this library online so as to be able to reference various ways to leverage this API. Consequently, I'm having to sift through the JavaDoc and sort of make guesses to try to get things working.

That being said, the examples that are provided are excellent and I was surprised how easy it was to get setup and basic acid-test working! It's just now I'm passed the basic test and need to do some more sophisticated stuff.

**Comment by ricellis** [comment]
Thank you for the feedback, I'm glad the examples were useful, but I was sorry to hear that it wasn't straightforward to find the more detailed ones in the javadoc. We have tried to keep the samples there because they are easier to maintain nearer the code they reference.
We didn't want them to get lost though so we tried to make the javadoc more navigable by including an overview on the first page, e.g. the one linked to at [API Reference (javadoc)](http://www.javadoc.io/doc/com.cloudant/cloudant-client/), which includes a table of contents to sections for the main features of the library that each link on to the appropriate section of javadoc.

Is that javadoc overview where you started your digging? I'm trying to get an idea if that overview page & table of contents was not obvious or if it was just awkward navigating from there to where you needed.

To answer your other question, yes, [query APIs](http://static.javadoc.io/com.cloudant/cloudant-client/2.4.1/overview-summary.html#Cloudant%20Query) are also available in the library.

**Comment by codyburleson** [comment]
OK, wow. Now that you pointed out the JavaDoc overview page, I actually looked at it and it is very informative. Also, I noticed that the packages have good overview information. I guess, to answer your question, that was not obvious to me. Initially, I landed on the JavaDoc page, didn't scroll down, looked at the list of classes on the left, and immediately started navigating to individual classes that looked like they might be helpful. I guess I'm so used to JavaDocs NOT being very informative that I completely had blinders on! In hindsight, I guess it could be helpful to explicitly spell it out at the end of the Getting Started samples on the main README.md page. For example:

More documentation is maintained in the JavaDoc API. The JavaDoc overview page, for example, has additional code samples and explanations. To find the additional information, be sure to scroll down past the auto-generated summary tables. Unlike a lot of JavaDocs you may have seen before, we've actually put a lot of usage examples in ours.

Anyway, great answer! I am now illuminated. I'll leave it up to you whether you want to add the additional hint on the main page, but I'mm closing this issue as satisfactory for me. Thanks!!!

**Comment by ricellis** [comment]
I appreciate you taking the time to explain and making a good suggestion. I've added an extra note to the README.
