### ISSUE TITLE
dataSize vs. diskSize?

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#261]
It seems there is not support for the `dataSize` property mentioned in the [couch API](http://docs.couchdb.org/en/latest/api/database/common.html#get--db).

On Cloudant due to compaction perhaps the difference is minimal.

**Comment by srl295** [comment]
On Cloudant there's also an undocumented `other.dataSize` with a different value…

**Comment by ricellis** [comment]
You can use the `client.executeRequest` method to perform calls that are not currently available in the Java API.
For example you could use `client.executeRequest(Http.GET(database.getDBUri()).responseAsString()` to get the JSON string rather than a `DbInfo` instance.
For Cloudant databases that response should have a `sizes` property like:
`"sizes":{"file":2835275,"external":3579,"active":11876}`

* `file` is equivalent to `disk_size`
* `external` is equivalent to `data_size`
* `active` is the amount of data in use
