### ISSUE TITLE
okhttp connection pool parameters - min connections , idle timeout

### ISSUE THREAD

**Issue by sagardiwan** [cloudant/java-cloudant#280]
We are trying to use the okhttp library for the first time with WebSphere. We upgraded WAS 8.5.5 JRE from 1.6 to 1.7 for using okhhtp.

Few questions in this regard - 
1) We intend to use connection pooling feature by initializing the pool with min number of connections, say 5. Is there a way to configure this ? 
2) We want to leave the connection open after a cloudant operation. However it seems that the connection is being closed automatically. Can this be avoided ? Does the jvm keep.alive property apply to okhttp also ?
3) Some of the forums indicate that JRE 1.7 dependency is only for building and not runtime. Would okhhtp work with WAS JRE 1.6 by adding as a shared lib ?
4) Is there a way to check if the cloudant library is using okhhtp ? Either through some API or enabling specific debug ?

**Comment by ricellis** [comment]
1. `ClientBuilder.maxConnections()` is how to configure the number of connections available to the okhttp connection pool. There is no minimum configuration the connections will grow as needed when requests are made up to the maximum.
2. The `keep.alive` property does not apply to okhttp. The connections are left open where possible. If connections are left idle (I think for 2.5 minutes) then they will be terminated by the server anyway so don't expect them to stay open for longer than that unless requests are ongoing. There were also some minor issues with connections not consuming streams in some circumstances, which I believe causes them to get closed early - we fixed some in version 2.5.1, more are fixed in master and will be in the next release.
3. I don't know, but probably not. It sounds like this might work for Android applications that use dex to remove some Java 7 code features, but probably doesn't work by default.
4. If you are using version 2.5.0 or higher then you can see a message if you enable `java.util.logging.Level.CONFIG` (or higher) level logging for `com.cloudant.client`. The message will say `Using OkHttp` or if it is not using okhttp then it will say `Using built-in HttpUrlConnection`.

**Comment by sagardiwan** [comment]
For our application to provide optimal response times, we believe it should be using already established connections. So in a way #1 and #2 in the list would be important. We are currently observing that the connections don't stay open even for 2.5 minutes. But it could be due to the older version we have been using (2.4.2). We will try with latest versions and check the results. But overall, the connection pooling here does not seem to be similar to the WAS datasource connection pools.

**Comment by sagardiwan** [comment]
An update - we tried with latest version 2.5.1 and still notice that the connections are getting closed almost immediately. So it seems that adding okhttp jars to our application may not provide the expected behavior of having a connection pool similar to DB connection pool. It would be a great feature to add for server side applications like ours.

**Comment by ricellis** [comment]
Do you have an example of the circumstances when you are seeing the problem, e.g. what calls/requests you are making?
Is it the same `save`/`find`/`update` as you reported in #247?
Did you validate from the logging that okhttp connection was being used and you are not being subjected to the short purge times we discussed in #247?

**Comment by sagardiwan** [comment]
Ok, we found this class, OkUrlFactory in okhttp-urlconnection.

https://mvnrepository.com/artifact/com.squareup.okhttp/okhttp-urlconnection

After we added this jar, we see that it is using okhttp and the connection stays alive for 2.5 mins. It would be great if we can keep it alive for longer. But at least for now the connections can be reused during peak volumes, if not all the time.

Thanks for your help!

**Comment by ricellis** [comment]
Yes, as shown in the [installation section of the readme](https://github.com/cloudant/java-cloudant#installation-and-usage) the necessary dependency for the optional okhttp support is okhttp-urlconnection at version 2.7.5 (for java-cloudant's cloudant-client 2.5.1).

Glad you were able to get it working. As I mentioned earlier 2.5 minutes is the server side timeout so we cannot influence that in the client. The server side value is chosen to ensure that connections do not persist for too long to allow, for example, failing over workload between load balancers and other necessary actions to maintain the service.
