### ISSUE TITLE
lightcouch: improve docs for View.query()

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#285]
FYI https://github.com/lightcouch/LightCouch/issues/60

> …when include_docs=false (as in a reduce), the Class<T> classOfT is applied to the entire row {key: …, value: …}, not just the value. This probably should be documented.

**Comment by ricellis** [comment]
Thanks for the headsup @srl295 but we don't consume lightcouch from upstream and we've diverged quite a bit, we don't have a lightcouch style view query since 2.0.

The view code in java-cloudant 2.x is parameterized by `<K>` key and `<V>` value classes. So we always treat the values separately as type `V`.

We have a convenience method on a `ViewRequest` for retrieving a single reduce result:
* [`request.getSingleValue()`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewRequest.java#L104)

Otherwise the `ViewResponse` has values and rows also typed by `<V>`, see:
* [`response.getValues()`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java#L50)
* [`response.getRows()`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java#L38)
    * [`row.getValue()`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java#L95)

If using include docs then the types of the row key and value are independent of the document type which is supplied as a class parameterized by `<D>`  for example when calling:
* [`response.getDocsAs(Class<D> docType)`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java#L68)
* [`row.getDocumentAsType(Class<D> docType)`](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/ViewResponse.java#L113)

**Comment by srl295** [comment]
@ricellis got it… thanks. I did see the request/response but forgot to double check when fililng this. Need to get off 1.2.0…
