### ISSUE TITLE
Unable to limt the number of HTTP connections made by cloudant client in IBM java

### ISSUE THREAD

**Issue by neekrish** [cloudant/java-cloudant#327]
I don't see a property http.maxConnections in IBM java 8 ... I try to fetch that and I get null .. Does that mean there is no limit on the number of connections created by cloudant? 

Also we are seeing large number of thread creation in the java client library of cloudant after moving from 2.5 to 2.6.2 ... Mostly due to increase in the number of connections made to cloudant. One of the stack traces indicates this .. Not sure where else the thread is getting created:
```
 java.lang.Thread.startImpl (Native Method)

                                java.lang.Thread.start (Unknown Source)

                                    com.ibm.jsse2.as.a (Unknown Source)

                                    com.ibm.jsse2.as.i (Unknown Source)

                                    com.ibm.jsse2.as.a (Unknown Source)

                       com.ibm.jsse2.as.startHandshake (Unknown Source)

    com.ibm.net.ssl.www2.protocol.https.c.afterConnect (Unknown Source)

         com.ibm.net.ssl.www2.protocol.https.d.connect (Unknown Source)

…et.www.protocol.http.HttpURLConnection.getInputStream0 (Unknown Source)

…net.www.protocol.http.HttpURLConnection.getInputStream (Unknown Source)

            java.net.HttpURLConnection.getResponseCode (Unknown Source)

 com.ibm.net.ssl.www2.protocol.https.b.getResponseCode (Unknown Source)

….http.interceptors.CookieInterceptor.interceptResponse (CookieInterceptor.java:142)

              com.cloudant.http.HttpConnection.execute (HttpConnection.java:358)

…m.cloudant.client.org.lightcouch.CouchDbClient.execute (CouchDbClient.java:481)

…ient.org.lightcouch.CouchDbClient.executeToInputStream (CouchDbClient.java:572)

  com.cloudant.client.org.lightcouch.CouchDbClient.get (CouchDbClient.java:328)

….cloudant.client.org.lightcouch.CouchDatabaseBase.find (CouchDatabaseBase.java:85)

                 com.cloudant.client.api.Database.find (Database.java:527)
```
- CloudantClient (java-cloudant) version(s) that are affected by this issue.
2.6
- Java version (including vendor and platform).
IBM java 8 in liberty buildpack of IBM bluemix

- If you're using the optional okhttp dependency.
NO

- A small code sample that demonstrates the issue.

**Comment by ricellis** [comment]
If the property is `null` it will use the default for the JVM, which I believe is normally 5 connections. I don't think changing java-cloudant client version would change the number of threads because it does not directly create any threads on its own. The JVM's `maxConnections` property only controls the size of the keep-alive connection pool it doesn't control the number of threads. The threads will be created by your application or framework.
The stack trace shows a thread doing a HTTP `GET` of a document, I don't see anything unusual about that. If you are using more than 5 connections at once (e.g. getting more than 5 documents in parallel) then some threads will have to wait to get a connection from the pool, but they should make progress when a connection becomes available.

**Comment by ricellis** [comment]
This has been inactive for some time, closing. Let me know if there are still questions/issues.
