### ISSUE TITLE
Separate internal GSON usage from user deserialization

### ISSUE THREAD

**Issue by ptommasi** [cloudant/java-cloudant#338]
Hi,

When I save a document in a database, any property which contains a null value is not stored in the db and, therefore, lost.

I think the problem comes from class `com.cloudant.client.org.lightcouch.CouchDbClient`, when I use `Database.save(Object)` a chain of calls lead to `CouchDbClient` method `public Response put(URI uri, Object object, boolean newEntity, int writeQuorum) { ... }`, which has the following line:
```
        final JsonObject json = getGson().toJsonTree(object).getAsJsonObject();
```

At runtime, above line parses 'object' and returns a JsonObject without any property with null values. 

Since it is quite deep in the code, I don't know how to change the behaviour of the gson object, is there a way to avoid the loss of properties with null values?

Some more details:
- CloudantClient (java-cloudant) version(s) that are affected by this issue: 2.4.3, 2.7.0
- Java version (including vendor and platform): JavaSE-1.7
- If you're using the optional okhttp dependency: yes (3.3.0)
- A small code sample that demonstrates the issue:

```
		/** Snippet start **/
		com.cloudant.client.api.Database db = client.database(dbName, create);

		String data = "{\"_id\":\"test\",\"prop\":null}";
		JsonElement doc = new Gson().fromJson(data, JsonObject.class);
		JsonObject docObj = doc.getAsJsonObject();
		log.info("JSON created: " + docObj.toString());

		db.save()
		/** Snippet end **/
```

**Comment by ricellis** [comment]
You can customize the GSON behaviour using [`ClientBuilder.gsonBuilder(GSONBuilder)`](http://static.javadoc.io/com.cloudant/cloudant-client/2.7.0/com/cloudant/client/api/ClientBuilder.html#gsonBuilder-com.google.gson.GsonBuilder-).

Although there is a `GSONBuilder.serializeNulls()` option I would advise against using that as it will break some of the internal library (de)serialization operations that rely on `null` being excluded. I'd like to distinguish the internal usage of GSON from the user facing functions at some point, but it is not currently the case.

Instead you can register a [customized serializer](https://github.com/google/gson/blob/master/UserGuide.md#custom-serialization-and-deserialization) for your class that handles the `null` as you like (assuming you are not using the GSON `JsonObject` as your type other than in the example).

Of course another option is to treat the absence of a property as `null`, but perhaps that doesn't suit your use case.

**Comment by ptommasi** [comment]
Sadly I'm writing an API which handles any JSON in input and stores it in Cloudant, therefore neither ignoring null value nor registering a type don't fit me!

Using `GsonBuilder.serializeNulls()` when I create a `CloudantClient` solved the issue, I hope there won't be side effects!

**Comment by pravingurav** [comment]
Can I use update handler instead of fetching document and sending fetched document with update to db.update() method?????

**Comment by ricellis** [comment]
This issue was left open to cover the work I mentioned earlier to separate the internal GSON usage from deserialization into user specified POJO types. The objective being that the user is free to specify GSON options without concern that fields will be deserialized differently for the cases where java-cloudant needs to deserialize things internally, such as this example for `serializeNulls`.

**Comment by ricellis** [comment]
We're not going to change this here. Our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) manages this separation because serialization/deserialization of POJOs is via using `InputStream` so the choice of serializer and options is completely in the user control. For the non-POJO built-in serialization case there then `null`s are serialized for user defined properties in the `Document` model.
