### ISSUE TITLE
Support generic Json Provider

### ISSUE THREAD

**Issue by shakedel** [cloudant/java-cloudant#352]
It is almost impossible to work with any other JSON Provider (e.g. Jackson) since GSON is fused into the code. 
Moving to a _Provider_ based code will increase potential users.

**Comment by ricellis** [comment]
Agreed. This is something we have discussed previously in our wish-list for the next major version and I hope that we'll be able to include it in the plans.

**Comment by shakedel** [comment]
I have begun working on this. Perhaps we discuss the specifics. I used an interface similar to the jax-rs `Provider` (basically implements `MessageBodyReader`and `MessageBodyWriter`) for all Object to/from JSON, and `javax.json`for the rest. Any other ideas?

**Comment by schotrain** [comment]
Even if there were something simple such as having some additional *find* methods that returned an inputstream that we could read and parse manually rather than forcing it through GSON, I'd be happy.

**Comment by shakedel** [comment]
Here is what I am currently using to work with Jackson. Note the many `UnsupportedOperationException`

[DatabaseJackson.txt](https://github.com/cloudant/java-cloudant/files/1017264/DatabaseJackson.txt)

**Comment by ricellis** [comment]
It may be worth noting that it is possible to execute to a stream via the [CloudantClient#executeRequest](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) method, but it does require manually building the request URL.

Our current proposal for future versions is to break the link between the construction of the request and the type of the response. As such the built request, at the most basic level, could be executed to a stream. At higher abstraction levels they could be executed to specific types via object mappers similar to the current API. This will make it much easier to leverage the API to facilitate building the request, but have the flexibility to consume the response in whatever way is preferred by the application. It will also give us the opportunity to re-structure in a way that makes it easier to add insertion points for custom serializers/deserializers.

**Comment by schotrain** [comment]
That proposal sounds exactly like what we're looking for.

**Comment by KingJam** [comment]
This issue is pretty old.  Has it been implemented yet?

**Comment by smithsz** [comment]
Hi @KingJam, This hasn't been implemented. I'm afraid this one isn't a priority for us right now. We have no immediate plans to make the enhancement. Apologies.

**Comment by smithsz** [comment]
Whoops, didn't mean to close!

**Comment by KingJam** [comment]
@smithsz The problem with using gson is that *all* jax-rs implementations use jackson as the provider. Not gson.  This means that a typical microservice with a REST API cannot easily use the cloudant java lib.  

I am an IBMer on a large customer project which uses Cloudant. I think you will find that supporting JAX-RS is important if you want Cloudant to be considered as a viable platform on future projects.

**Comment by sheinbergon** [comment]
@smithsz  If this was to be implemented, would you be willing to accept a PR?

**Comment by ricellis** [comment]
@sheinbergon Thanks for offering we would _potentially_ be willing to accept a PR for this feature.

Our current focus for this library is keeping pace with Cloudant features rather than major enhancements to the design of the library itself. As such I think any proposed PR would have to be within a well-defined scope in addition to being subject to the usual contribution guidelines and review process.

Specifically:
* At this point in time we would not accept the type of restructure proposed in my [earlier comment on this issue](https://github.com/cloudant/java-cloudant/issues/352#issuecomment-305830303) as it would involve breaking API changes
* Any proposed change would have to be limited to the methods where the user provides a class for deserialization, that is, the existing model classes should continue to be internally deserialized by GSON using the options we specify. Effectively the separation proposed in #338 is a prerequisite or needs to be part of this work.
* A proposed solution could provide an option (likely an interface) for adding a custom serializer/deserializer and a default GSON implementation such that if unset existing usage would continue unchanged. Besides this option there should be no API changes. We would be open to discussing other options, but I anticipate this to be the least invasive route.
* I think we would be unlikely, at least at this time, to also ship a Jackson implementation within the library because of the additional support requirement for those new code paths, but obviously with the option available it would be trivial for users or another project to supply a compatible implementation.

**Comment by bram209** [comment]
Any update on this?

**Comment by emlaver** [comment]
Hi @bram209, there are no updates and this item is currently not a priority for our team right now.

**Comment by sheinbergon** [comment]
@bram209  @emlaver  for it's worth, I give this a shot some time ago.

Unfortunately, Gson is indeed entangled with the internal data layer of this library. 

While simple get/set custom json encoding would be easily achievable while complying to the requirements specified above, Implementing a complete solution in a generic fashion is a bit problematic due to differences in approaches to type tokenization (Jackson does it in completely a different fashion).

**Comment by ricellis** [comment]
We're not going to make this change here. However, our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) includes streaming `InputStream` versions of the operations that send or receive document structures with the server, which makes it possible to pass the bytes to any chosen serialization/deserialization provider.
