### ISSUE TITLE
Add Timeout replay interceptor

### ISSUE THREAD

**Issue by KingJam** [cloudant/java-cloudant#353]
We had a recent Cloudant incident where some nodes in the cluster were not responding and eventually timed out with a 500 error.  This disabled our app.

Is it possible to add a retry mechanism based on 500 error and/or request timeouts?

**Comment by ricellis** [comment]
I think you will need to take care with this approach - if nodes are unresponsive the system is likely already under strain and retrying requests will probably just make that problem worse, by increasing the load on the system further. You probably have already, but I would recommend that you talk to support@cloudant.com about the issues with the nodes and what root causes might have been a factor.

That said if you want to do this it is possible to add interceptors via the [`ClientBuilder#inteceptors()` method](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/ClientBuilder.html#interceptors-com.cloudant.http.HttpConnectionInterceptor...-). You could, for example, follow the pattern of our [Replay429Interceptor](https://github.com/cloudant/java-cloudant/blob/master/cloudant-http/src/main/java/com/cloudant/http/interceptors/Replay429Interceptor.java) to make a similar interceptor to retry in response to a `500` status code.

If you are getting, say, `SocketTimeoutException` on the client side without a server response it is more complicated. You can adjust the duration of the client side read timeout with [`ClientBuilder#readTimeout()`](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/ClientBuilder.html#readTimeout-long-java.util.concurrent.TimeUnit-), but to replay is more challenging because the `IOException` is not within the scope of the interceptors. One option would be to wrap your request in a `try/catch` and inspect the cause of the `CouchDbException` to see if it was an instance of a`SocketTimeoutException` and then repeat the request if it was.
