### ISSUE TITLE
How to avoid "Cloudant QL Injection" for parameters? How to properly escape parameters?

### ISSUE THREAD

**Issue by tobilarscheid** [cloudant/java-cloudant#359]
Hi guys,

just a quick question I could not quite wrap my head around from looking at the docs. From the official docs I can not really see how injection is avoided, e.g. if I consider this code snippet:

```java
public String toString() {
    return "{ id: " + _id + ",\nrev: " + _rev + ",\nisExample: " + isExample + "\n}";
  }
```

How do I avoid that if I set `isExample = "\", \"hackyField\": \"it work's\""` I end up with a document like this:
```json
{
  "id": "1",
  "_rev": "1",
  "isExample": "",
  "hackyField": "it work's"
}
```

I assume this is probably even more problematic for things like `_find` etc.

Any feedback is appreciated.

**Comment by tobilarscheid** [comment]
Okay, I prepared this very 'minimal' example:

```java
import java.net.MalformedURLException;
import java.net.URL;

import com.cloudant.client.api.ClientBuilder;
import com.cloudant.client.api.CloudantClient;
import com.cloudant.client.api.Database;

public class Main {

    public static void main(String[] args) throws MalformedURLException {
        CloudantClient client = ClientBuilder.url(new URL("http", "localhost", 5984, "")).build();
        Database db = client.database("test", false);
        db.save(new MyObject());
    }

    private static final class MyObject {
        private String _id = null;
        private String _rev = null;
        private String param = "test\",\"hack\":\"it\"";

        public String get_id() {
            return _id;
        }

        public void set_id(String _id) {
            this._id = _id;
        }

        public String get_rev() {
            return _rev;
        }

        public void set_rev(String _rev) {
            this._rev = _rev;
        }

        public String getParam() {
            return param;
        }

        public void setParam(String param) {
            this.param = param;
        }
    }
}
```
It results in the following document:
```json
{
  "_id":"6d7f252c06bb4c91a22a4755015f48e5",
  "_rev":"1-3e4921701abc36a68353ece54274c248",
  "param":"test\",\"hack\":\"it\""
}
```

So deep down in the `CouchDb Client` escaping the json is properly handeled (actually it's the GSO N Serialization). I do however then feel that the example with the jsonifying-`toString` method is quite misleading and should be changed. The question remains if the same applies for find etc.

**Comment by ricellis** [comment]
As you point out the library performs conversion of document `Object` types and `selector` strings via GSON. We have some in-built adapters for internal objects, but otherwise the library uses the [default GSON conversions](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Using-Gson) for primitives etc unless you register specific `TypeAdapter`s or (de)serializers of your own.

As you have seen these defaults will correctly escape string content where it is contained in a field to be serialized.

However, the library cannot make assumptions about what selectors or document contents are valid for any given application. As an application using java-cloudant it is your responsibility to sanitize data appropriately before passing it to the library's methods.

For example when writing your application you should not expose the methods from `Database` directly to end users as it would be trivial to perform an "injection" by arbitrarily trying document IDs or supplying a selector that retrieved other documents.

For example if your application was to provide some sort of search it should accept search terms and sanitize and escape them before building the `selector` string to pass to the `Database#findByIndex()` method. The application user should not have direct access to provide a selector.

Regarding the `README` content, the `ExampleDoc` class has a `toString()` method that outputs JSON simply from the perspective of demonstrating that the JSON document content has been retrieved from the database and deserialized into an instance of the `ExampleDoc` class. The object model that you choose for your application is up to you and can include whatever fields and methods you need (although you should include `_id` and `_rev` or equivalent fields that a GSON adapter can convert to/from `_id` and `_rev` in the JSON document).

If you don't want to use specific classes to model your application you can use `Map<String, Object>` or GSON's `JsonObject` as the class type for your documents or possibly register a `TypeAdapter` to use another Java JSON container class.
