### ISSUE TITLE
Query and return the index of the doc in a data set

### ISSUE THREAD

**Issue by Mr-OUCH** [cloudant/java-cloudant#45]
Hi, I'm trying to figure out if it is possible to run a query for a particular key-value-pair with a customized sort setting and then in the returned doc it will returns the index of the doc in the database along with the doc. Do you think it is doable? Thanks.

For example:
I have a database that has 10 docs, and I am looking up the one with name=john, with sorting on address. I wish Cloudant can return me the doc that has name=john while also letting me know its index in this data set with sorting applied is 5.

**Comment by mariobriggs** [comment]
'while also letting me know its index in this data set with sorting applied is 5.' - for a sec u had me wondering if that 'sort' referred to the sort on address, but that can't be the case since one can decipher that from the result.
I am a little curious what the higher level use-case is that u are going after.

**Comment by bradley-holt** [comment]
If I understand the question correctly, you have 10 docs. You have a map function which indexes the `name` field of these docs. If you were to return all 10 results of this index by name you would see (for example):

1. Andrew
2. Ashley
3. Bessie
4. Everett
5. John
6. Karl
7. Lee
8. Lora
9. Louise
10. Ollie

You want to run a query for all documents having the `name` field with a value of "John". However, you don't just want the results, you want to know where in the above list the results are. Meaning, you want to know that "John" is at position 5. Is this correct?

**Comment by SteveChenTech** [comment]
Thanks, @bradley-holt yes, that's correct. To make it a little complicated than your excellent example  - besides the index and name columns, there is a third column named "zip code". The use case is to sort on "zip code" and then find the row with name="John" and the index of this row.

@mariobriggs, the high level use case is the application wants to first find a particular record (e.g., row with name="John" in @bradley-holt 's example) and then use the row's index to apply pagination. Thanks!

**Comment by alkos333** [comment]
Let's assume you have a dataset with the following columns: name, zipcode.  You would like this dataset to be sorted by zipcode, so you've probably created an index using Cloudant Query like so:

```http
curl -X POST -d '{
    "index": {
        "fields": [
            {"zipcode": "asc"},
            {"name": "asc"}
            
        ]
    },
    "name": "zipcode-name",
    "ddoc": "zipcode-name"
}' https://account.cloudant.com/db/_index
```
Cloudant Query has defined a design doc for you named "_design/zipcode-name" which essentially contains a MapReduce view:
```javascript
{
  "_id": "_design/zipcode-name",
  "_rev": "1-9b5c5a6b2d1f986f53766e75e61e0de5",
  "language": "query",
  "views": {
    "zipcode-name": {
      "map": {
        "fields": {
          "zipcode": "asc",
          "name": "asc"
        }
      },
      "reduce": "_count",
      "options": {
        "def": {
          "fields": [
            {
              "zipcode": "asc"
            },
            {
              "name": "asc"
            }
          ]
        },
        "w": 2
      }
    }
  }
}
```
So now you can query it using /db/_find endpoint, but you can also use it via /db/_design/zipcode-name/_view/zipcode-name endpoint directly:
```http
curl -X GET https://account.cloudant.com/db/_design/zipcode-name/_view/zipcode-name?reduce=true&endkey=["John", "20066"]
```
Two things to notice here:

1. reduce={true,false}  can trigger aggregations defined on the view. In our case that's _count.
2. we can also specify the startkey and endkey.  The key is determined by the **fields** array attribute that was used to create our zipcode-name. In this case, the key is an array of [name, zipcode]. 

So all you have left is determine what your endkey needs to be and with reduce=true, you'll get a number of records up to and including that endkey.

You already know the name because that is what you are searching by.  You need to figure out what the corresponding zipcode is for the first occurence of say "John" in the in the index. To do that you can define another index but flip the order of columns like so:
```http
curl -X POST -d '{
    "index": {
        "fields": [
            {"name": "asc"},
            {"zipcode": "asc"}
            
        ]
    },
    "name": "name-zipcode",
    "ddoc": "name-zipcode"
}' https://account.cloudant.com/db/_index
```
So to figure out your endkey given that name = "John", you can query this view like so:
```http
curl -X POST -d '{
    "selector": {"name":{"$eq": "John"}},
    "sort": [{"name": "asc"}, {"zipcode": "asc"}],
    "limit": 1
}' https://account.cloudant.com/db/_find
```
Once you construct the endkey, you can query against the first view using /db/_design/zipcode-name/_view/zipcode-name with reduce=true and the endkey you just prepared.

**Comment by ricellis** [comment]
Closing this issue as I don't think any changes are required from this.
