### ISSUE TITLE
Sorting on the result set is not happening with java code

### ISSUE THREAD

**Issue by TigerAVAF6R** [cloudant/java-cloudant#455]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
We are using one index query to return a result, we are using "sort" key word to do sorting based on a timestamp field, and set limit to 1, this means we want to get the latest one record, but we found that the query is working fine in browser dashboard, but not working in java code with api. We have created related index in cloudant already, we are not sure the reason behind this.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Below is the sample code we are using:

String query = {"selector":{"requestMethod":"xxx","profileID":"xxx"},"sort":[ {"createdTS:string": "desc"} ],"limit":1}
List<AuditLogBean> auditLogList = auditlogdb.findByIndex(query, AuditLogBean.class);

### 2. What you expected to happen
we expected the returned list has only one record, and the record is the latest one record

### 3. What actually happened
it is returning all record in a list, but no sorting happened on the records

## Environment details
- Version(s) that are affected by this issue.
    > 2.9.0
- Java version including vendor and platform
    > 1.8 IBM JDK
- Using the optional okhttp dependency.
    > Yes

**Comment by tomblench** [comment]
I would recommend POSTing to the `/_find` endpoint with `curl` or similar using the contents of `query`. If the result is not what you are expecting, then your query is wrong.

We recommend the use of `QueryBuilder` (sample [here](https://static.javadoc.io/com.cloudant/cloudant-client/2.13.0/com/cloudant/client/api/Database.html#query-java.lang.String-java.lang.Class-) which makes life easier since you don't have to worry about string escaping etc. There are options for sort, limit, etc.

**Comment by emlaver** [comment]
Closing as stale, please reopen if you require further assistance.
