### ISSUE TITLE
wsjar protocol

### ISSUE THREAD

**Issue by Emoney0321** [cloudant/java-cloudant#46]
Could a check for wsjar be added, in addition to jar and file, to the org.lightcouch.internal.CouchDbUtil.listResources(String path) method.  I am using WebSphere Liberty 8.5.5.5 and that method returns null for a path like the following: 
wsjar:file:/somepath/myapp.war!/WEB-INF/classes/design-docs/my-filter/

**Comment by mariobriggs** [comment]
if u can issue a Pull Request, i can take a look

**Comment by ricellis** [comment]
@Emoney0321 since version 8.5.5.2 it is possible to [configure the WebSphere Liberty profile to use jar: URLs](http://www-01.ibm.com/support/docview.wss?uid=swg1PM99378) by adding the element `<classloading useJarUrls="true"/>` to the server.xml. Please note that for Windows using jar instead of wsjar will lock the files, which will limit the ability to overwrite them.

Does this solution meet your needs?

**Comment by ricellis** [comment]
Closing as a workaround has been suggested. Please re-open if the workaround does not work for you.

**Comment by Emoney0321** [comment]
Yes, this will work.  Thanks for the link @ricellis.
