### ISSUE TITLE
Handle new_edits parameter on PUT (save, update) to avoid creation of conflict document

### ISSUE THREAD

**Issue by hufon** [cloudant/java-cloudant#517]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description

On API documents, there's a new_edits parameter on put request https://docs.couchdb.org/en/stable/api/document/common.html#put--db-docid
This parameter is important because it avoids creation of conflict documents in the db. By default it's true...

On Java cloudant API there's no way to set this parameter on save

### 2. What you expected to happen

You should have a parameter to update method to pass new_edits

### 3. What actually happened

On Java cloudant API there's no way to set this parameter on save

**Comment by mojito317** [comment]
Hi @hufon!

The default `"new_edits": true` is exactly the setting that prevents the insertion of conflicting documents. If you would not like to create conflicts _intentionally_, this is the setting you need, and it is not necessary to set it.

If you do want to change it to `false` that _will not_ prevent document conflicts, but I assume here it is not the plan, then I would recommend taking a glance at our new beta library where the `new_edits` property can be set as well: https://github.com/IBM/cloudant-java-sdk

If you are interested in what kind of conflicts can happen in a database inevitably I would recommend reading [this Cloudant blog post](https://blog.cloudant.com/2015/01/12/Introduction-to-Conflicts-Part-One.html):
>One of the consequences of eventual consistency is that documents might enter a conflicted state if the same version of a document is modified in different ways on two disconnected nodes.
...
>Even in a small Cloudant cluster, a conflict can arise if changes to the same document are sent to two nodes at the same time.
etc

**Comment by hufon** [comment]
with default new_edits: true i have conflicts documents when i got a 419 precondition failed.

**Comment by mojito317** [comment]
Can you please show a code snippet or a curl example where you get a `419`? If I understand correctly you would like to use the PUT `/{db}/{doc_id}` endpoint, do not you?

If you set `"new_edits": true`, it is natural behavior the server will ignore all modifications that might cause conflicts. It warns you of a problematic update request. In other words: your request is rejected because it would create a conflict.
This way you need to fix your document _client-side_ first, then you can upload the resolved document to your database. E.g. get the latest version of the document, merge it with your uploadable one using the current rev then update it.

If you set `"new_edits": false`, the server will allow creating conflicting documents in the database.
This way the responsibility is also yours to resolve the _server-side_ conflicts, but with a special technique. See the [How to resolve conflicts](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-conflicts#how-to-resolve-conflicts) section in the Cloudant documentation.

**Comment by hufon** [comment]
In fact, we have conflict when using saveAttachment method.

**Comment by mojito317** [comment]
Is your document rev up-to-date when calling `saveAttachment`?

**Comment by hufon** [comment]
yes we try ,  but sometimes, when under load we are in racecondition, where the document has been updated between getting lastest rev and saveAttachment... and the problem that we have, is that saveAttachment create conflicts revisions

**Comment by mojito317** [comment]
> yes we try , but sometimes, when under load we are in racecondition, where the document has been updated between getting lastest rev and saveAttachment...

Now it looks like more an architectural problem than a problem with the client lib itself.

Complete app design is outside the scope of an issue here. If you are an IBM Cloudant or Support for CouchDB customer you can email support@cloudant.com to setup an engagement with our Client Architecture team for more help designing your application. If you are not a customer then I'd recommend the [CouchDB slack ](https://couchdb.apache.org/#chat)or [users mailing list](https://couchdb.apache.org/#mailing-lists) to have discussions with the wider CouchDB community about best-practices for this type of application.

**Comment by ricellis** [comment]
Closing this as there is no change needed here.
* As pointed out in linked documentation above there are various race conditions that cannot be avoided with Couch 2.x and 3.x systems.
* AFAICT `new_edits` isn't applicable to attachment PUT
* We won't add the `new_edits` option to document PUT here - I'd recommend against it because intentionally overriding the conflict check and creating conflicts in the server revision tree will almost inevitably cause issues, but if you really wanted to do it you can workaround by using [`executeRequest`](https://www.javadoc.io/static/com.cloudant/cloudant-client/2.19.1/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) to make a custom request with the option.
