### ISSUE TITLE
more efficient sync?

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#77]
This is maybe a lightCouch q, but I wonder if `synchronizeWithDb` could be made more efficient with something such as:
* md5 hash the document, do a query including that hash?
* keep a 'revision number' in the js file (manually updated) and only sync if it changes?

**Comment by ricellis** [comment]
This API changed in 2.0.0, the equivalent functionality now is `Database.getDesignDocumentManager().put(DesignDocument)`.

This method performs a `GET` of the design document from the database and does an equality check with the supplied `DesignDocument` (which can be obtained from a js file with `DesignDocumentManager.fromFile()`). If the equality check fails then an update will be performed, but not otherwise.

I think to get the behaviour you want you just need to make sure that the `_rev` of the design document is up-to-date in your js file after a sync (so that the documents will be equal if there are no other changes). You can get it from the `Response` object returned from the `put`.

**Comment by ricellis** [comment]
Closing based on the above.
